### ISSUE TITLE
filesystem access issues running LLVM tests

### ISSUE THREAD

**Issue by kstuart** [debarshiray/fedora-toolbox#10]
Great tool, thanks (specially for us folks new to silverblue)

Building LLVM seems to work, however I'm seeing filesystem access issues when attempting to run the tests.

Possibly related to #9

**Environment:**

fedora-silverblue: 29.20181101.0 (2018-11-01 14:01:23)
fedora-toolbox: cf2347fe562dd78210c7245f5ded268d8ea7f18a

runc version 1.0.0-rc5+dev
commit: 7463241d645ba55b05b103673e322542661b0ad8
spec: 1.0.1-dev

/var/home btrfs rw,nodev,noatime,seclabel,compress=zstd,ssd,space_cache,subvol=/home

**Steps to reproduce:**

1. Create a default fedora-toolbox and enter it
2. `sudo dnf update -y && sudo dnf builddep -y llvm`
3. `sudo dnf install -y svn`
4. create and/or cd into `$HOME/src`
5. `svn co http://llvm.org/svn/llvm-project/llvm/trunk llvm`
6. `cd llvm && mkdir build && cd build`
7.
```
cmake -GNinja \
  -DCMAKE_INSTALL_PREFIX=/opt/llvm \
  -DCMAKE_BUILD_TYPE=Release \
  -DLLVM_USE_LINKER=gold \
  -DLLVM_OPTIMIZED_TABLEGEN=ON \
  -DLLVM_USE_SPLIT_DWARF=ON \
  ..
```
8. run `ninja check-llvm`

**Expected:** LLVM tests to run successfully

**Actual: (cut out the traceback for brevity/readability)**
```
Running the LLVM regression tests
                                       -- Testing: 28397 tests, 16 threads --                                      
0% [------------------------------------------------------------------------------------------------------------]
OSError: [Errno 30] Read-only file system
FAILED: test/CMakeFiles/check-llvm 
ninja: build stopped: subcommand failed.
```

**Comment by debarshiray** [comment]
That was with LLVM commit 10c750cc3f45be8d.

**Comment by debarshiray** [comment]
Sounds great! Thanks for getting in touch.

**Comment by debarshiray** [comment]
Duplicate of #9
