### ISSUE TITLE
Own PS1 in .bashr override

### ISSUE THREAD

**Issue by marusak** [debarshiray/fedora-toolbox#11]
I use my own PS1. I have it in my `.bashrc` file like `export PS1=...` which overrides the one passed to container. And then it is really confusing if I am in toolbox or on my machine.

Is there some simple way how to easily recognize from toolbox that I am inside (so I can edit my PS1 to recognize this)?

**Comment by krashekspres** [comment]
$HOSTNAME is toolbox in toolbox

**Comment by marusak** [comment]
Thank you for the hint.
Prepending `$(if test $HOSTNAME = "toolbox"; then echo -n "🔹[\u@\h \W]\\$ "; fi;)` to my PS1 solves this issue :)
