### ISSUE TITLE
/dev/fuse not available in the toolbox

### ISSUE THREAD

**Issue by Logibox** [debarshiray/fedora-toolbox#15]
Is it possible to add a `--volume /dev/fuse:/dev/fuse` when creating the toolbox to facilitate this?

**Comment by debarshiray** [comment]
@Logibox does #36 help?

It would be nice to know your use-case so that I could test that it actually works as intended. :)

**Comment by Logibox** [comment]
Thanks, that patch looks like it would do the job, but I'm not at my workstation now to test it :(.

The reason I raised the issue was I find myself using [sshfs](https://github.com/libfuse/sshfs) in my workflows, and couldn't inside the toolbox.

**Comment by debarshiray** [comment]
Closing, after @Logibox confirmed the fix in #36.
