### ISSUE TITLE
sudo doesn't work! (When using 'overlayfs' driver)

### ISSUE THREAD

**Issue by Logibox** [debarshiray/fedora-toolbox#23]
```
[myates@myates-uk-rdlabs-hpecorp-net fedora-toolbox]$ fedora-toolbox create
[myates@myates-uk-rdlabs-hpecorp-net fedora-toolbox]$ fedora-toolbox enter
🔹[myates@toolbox ~]$ sudo -i
sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
🔹[myates@toolbox ~]$ logout
[myates@myates-uk-rdlabs-hpecorp-net fedora-toolbox]$ buildah --version
buildah version 1.5 (image-spec 1.0.0, runtime-spec 1.0.0)
[myates@myates-uk-rdlabs-hpecorp-net fedora-toolbox]$ podman --version
podman version 0.10.1.3
[myates@myates-uk-rdlabs-hpecorp-net fedora-toolbox]$ rpm-ostree status --booted
State: idle
AutomaticUpdates: disabled
BootedDeployment:
● ostree://fedora-workstation:fedora/29/x86_64/silverblue
                   Version: 29.20181205.0 (2018-12-05T01:01:39Z)
                BaseCommit: 6b4bc8e81acb50897c493154d09afb6f07da3b2d35a1811ab1f121c4447117c1
              GPGSignature: Valid signature by 5A03B4DD8254ECA02FDA1637A20AA56B429476B4
           LayeredPackages: neovim powerline-fonts python2 python3-neovim rpm-build strace the_silver_searcher tmux vim zsh
             LocalPackages: tube-certificates-2.0.0-3.el7.vduos.noarch

```

Obviously this is a bit of an issue as you can't use `dnf` without `sudo`, which make the toolbox a bit useless.

**Comment by Logibox** [comment]
Ah update - this seems to be when using the `overlayfs` driver for the storage backed - changing this config fixes the issue:
```
~/.config/containers/storage.conf
[storage]
driver = "vfs"
```

**Comment by jgillich** [comment]
How do you apply this change? I tried deleting the container and image, but that didn't help.

**Comment by smlloyd** [comment]
Changing the driver in storage.conf didn't seem to have any effect for me either - I was always ending up with a container using overlayfs.

I did get fedora-toolbox to create a container with vfs using the STORAGE_DRIVER environment variable, however. Maybe this is a podman or buildah bug?

**Comment by Logibox** [comment]
I'm not entirely sure of the mechanics, but podman embed the driver somewhere in ~/.local/share/container/storage. Removing this dir will cause it to fallback on what is specified in ~/.config/containers/storage.conf (obviously this solution might not be practical for everyone).

**Comment by Logibox** [comment]
Also there seems to have been a change in format for this file that hit buildah and podman at different times see: https://github.com/containers/buildah/issues/1224. @leonardo2707 I think you've ended up with these formats mixed up.

**Comment by Logibox** [comment]
Update: podman stores it's config/state in ~/.local/share/containers/storage/libpod/bolt_state.db. Deleting that should be enough to force a new graph driver.

**Comment by debarshiray** [comment]
This was fixed by https://github.com/containers/fuse-overlayfs/pull/32
