### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by rugk** [debarshiray/fedora-toolbox#40]
The doc seems to be a good start, but at the end of the Readme I still only have a shell.

I do not know:
* what this project really wants to solve (I mean, the ostree image is fixed, okay, but what can I do now what I could not do before?)
* how to use it (these two commands won't be the only ones)
* seeing it does some container stuff, what about: compartmentalization (create a new "container" and change stuff there?), rollback (can I also quickly delete/dismiss a container?), advantages of this(?)…
* what I can actually do inside of it?

If you want an example use case take [full system backups, e.g. with `borgbackup`](https://discussion.fedoraproject.org/t/how-are-we-supposed-to-handle-do-backups/751) and possibly [some wrapper scripts](https://github.com/rugk/borg-cron-helper) and where you need to [setup](https://github.com/rugk/borg-cron-helper/wiki/How-to-setup%3F) a cron job or systemd timer, and special stuff like that. Or even advanced stuff like notifications (i.e. `zenity`), which I guess is a little hard to make work manually. (I know, flatpak can do so, of course, but manually – this needs some doc)

**Comment by debarshiray** [comment]
@cgwalters reworked the `README.md` in #43  It would be good to have some manual pages too.

> * what this project really wants to solve (I mean, the ostree image is fixed,
> okay, but what can I do now what I could not do before?)
>
> ...
>
> * what I can actually do inside of it?

The earlier version of the `README.md` still had this text:
```
... use DNF to install your favorite packages, all without worrying about breaking
your operating system.
```

Ultimately, once you actually start using Silverblue, it becomes obvious what Fedora Toolbox aims to solve or why you would want to use it. :)

> If you want an example use case take [full system backups, e.g. with `borgbackup`](https://discussion.fedoraproject.org/t/how-are-we-supposed-to-handle-do-backups/751)
> and possibly [some wrapper scripts](https://github.com/rugk/borg-cron-helper) and where
> you need to [setup](https://github.com/rugk/borg-cron-helper/wiki/How-to-setup%3F) a cron
> job or systemd timer, and special stuff like that.

Umm... I don't think we can describe all the different things that one could possibly do inside the toolbox environment. After all, it's a full-fledged RPM based userspace environment.

> Or even advanced stuff like notifications
> (i.e. `zenity`), which I guess is a little hard to make work manually.

What do you mean by "manually"? Notifications should just work the same way they always did and do on the host. For example, try:
```
$ gdbus call --session --dest org.gtk.Notifications --object-path /org/gtk/Notifications --method org.gtk.Notifications.AddNotification "org.gnome.Terminal" "fedora-toolbox: hello world" "@a{sv} [{'title', <'Hello World'>}, {'body', <'Say hello to Fedora Toolbox'>}]"
```
