### ISSUE TITLE
Using custom images

### ISSUE THREAD

**Issue by mchacon-ml** [debarshiray/fedora-toolbox#44]
Hi!
I do not see how to use an extra images data from the image directory. I want to build a custom image using my own extra-packages file, but I do not see how to use my own configuration file.

Thanks!

**Comment by debarshiray** [comment]
You are free to build your custom image whichever way you want to. :) I'd only suggest layering it on top of the `fedora-toolbox` image.

The files inside the `images` sub-directory are meant to be the sources for the `fedora-toolbox` image. You can either tweak them locally to build your own images, or use an entirely different Dockerfile, or something else.

There's no configuration file. There's a `--image`  flag that you can pass to `fedora-toolbox create`. See `--help`.
